name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: sudo docker build -t amitkumar023/e-commerce  .
      - name: Publish Image to docker hub
        run: sudo docker push amitkumar023/e-commerce:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull amitkumar023/e-commerce:latest
      - name: Delete old container
        run: sudo docker rm -f e-commerce-container
      - name: Run Docker Container
        run: sudo docker run -d -p 4000:4000 --name e-commerce-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' amitkumar023/e-commerce
